const dummyDoctors = [
    {
        id: 1,
        name: "Dr. Mohammad Shah Alam",
        specialty: "Arthroscopy & Arthroplasty Surgeon",
        rating: "4.7/5",
        experience: "37+ Years Experience",
        consultationFees: [
            { method: "Cash", amount: "1000 Taka" },
            { method: "Bkash", amount: "800 Taka" },
        ],
        hospital: "York Hospital Limited",
        image: "https://images.pexels.com/photos/3279197/pexels-photo-3279197.jpeg",
    },
    {
        id: 2,
        name: "Dr. Sarah Khan",
        specialty: "Cardiologist",
        rating: "4.9/5",
        experience: "15+ Years Experience",
        consultationFees: [
            { method: "Cash", amount: "1200 Taka" },
            { method: "Bkash", amount: "1000 Taka" },
        ],
        hospital: "City Heart Clinic",
        image: "https://images.pexels.com/photos/5215024/pexels-photo-5215024.jpeg",
    },
    {
        id: 3,
        name: "Dr. Anwar Hossain",
        specialty: "Neurologist",
        rating: "4.8/5",
        experience: "20+ Years Experience",
        consultationFees: [
            { method: "Cash", amount: "1500 Taka" },
            { method: "Bkash", amount: "1300 Taka" },
        ],
        hospital: "Bangladesh Brain Institute",
        image: "https://images.pexels.com/photos/8460155/pexels-photo-8460155.jpeg",
    },
    {
        id: 4,
        name: "Dr. Maria Akter",
        specialty: "Gynecologist",
        rating: "4.6/5",
        experience: "18+ Years Experience",
        consultationFees: [
            { method: "Cash", amount: "1100 Taka" },
            { method: "Bkash", amount: "900 Taka" },
        ],
        hospital: "Women's Care Hospital",
        image: "https://images.pexels.com/photos/3845753/pexels-photo-3845753.jpeg",
    },
    {
        id: 5,
        name: "Dr. Kamal Uddin Ahmed",
        specialty: "Orthopedic Surgeon",
        rating: "4.5/5",
        experience: "22+ Years Experience",
        consultationFees: [
            { method: "Cash", amount: "1400 Taka" },
            { method: "Bkash", amount: "1200 Taka" },
        ],
        hospital: "Central Orthopedic Hospital",
        image: "https://images.pexels.com/photos/8376277/pexels-photo-8376277.jpeg",
    },
    {
        id: 6,
        name: "Dr. Nabila Rahman",
        specialty: "Pediatrician",
        rating: "4.9/5",
        experience: "10+ Years Experience",
        consultationFees: [
            { method: "Cash", amount: "1000 Taka" },
            { method: "Bkash", amount: "850 Taka" },
        ],
        hospital: "Little Angels Pediatrics",
        image: "https://images.pexels.com/photos/5327581/pexels-photo-5327581.jpeg",
    },
    {
        id: 7,
        name: "Dr. Rafiq Islam",
        specialty: "Dermatologist",
        rating: "4.7/5",
        experience: "14+ Years Experience",
        consultationFees: [
            { method: "Cash", amount: "1300 Taka" },
            { method: "Bkash", amount: "1100 Taka" },
        ],
        hospital: "Skin Care Clinic",
        image: "https://images.pexels.com/photos/8460157/pexels-photo-8460157.jpeg",
    },
    {
        id: 8,
        name: "Dr. Yasmin Kabir",
        specialty: "Endocrinologist",
        rating: "4.8/5",
        experience: "17+ Years Experience",
        consultationFees: [
            { method: "Cash", amount: "1200 Taka" },
            { method: "Bkash", amount: "1000 Taka" },
        ],
        hospital: "Diabetes & Hormone Care Center",
        image: "https://images.pexels.com/photos/8460160/pexels-photo-8460160.jpeg",
    },
    {
        id: 9,
        name: "Dr. Farhan Siddique",
        specialty: "Ophthalmologist",
        rating: "4.6/5",
        experience: "12+ Years Experience",
        consultationFees: [
            { method: "Cash", amount: "1100 Taka" },
            { method: "Bkash", amount: "900 Taka" },
        ],
        hospital: "Vision Care Hospital",
        image: "https://images.pexels.com/photos/8460156/pexels-photo-8460156.jpeg",
    },
    {
        id: 10,
        name: "Dr. Tahmina Akhter",
        specialty: "Psychiatrist",
        rating: "4.9/5",
        experience: "21+ Years Experience",
        consultationFees: [
            { method: "Cash", amount: "1600 Taka" },
            { method: "Bkash", amount: "1400 Taka" },
        ],
        hospital: "Mind Wellness Center",
        image: "https://images.pexels.com/photos/8460161/pexels-photo-8460161.jpeg",
    },
];

export default dummyDoctors;
