import {Geist, Geist_Mono, Inter, Poppins} from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import Footer from "@/app/footer";
import Testimonials from "@/components/shared/Testimonials";
import Newsletter from "@/components/news-letter/news-letter";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import ApolloWrapper from "@/components/apollo/ApolloWrapper";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const poppins = Poppins({
    variable: "--font-poppins",
    weight: ["300", "400", "500", "600", "700"],
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body
            className={`${poppins.variable} bg-[#F0F0F0]`}
        >
            <ApolloWrapper>
                <Header/>
                {children}
                <Testimonials/>
                <Newsletter/>
                <Footer/>
            </ApolloWrapper>
        </body>
        </html>
    );
}
