import Footer from "@/app/footer";
import ApolloWrapper from "@/components/apollo/ApolloWrapper";
import Header from "@/components/header/Header";
import BlogCardPreview from "@/components/news-letter/BlogCardPreview";
import Testimonials from "@/components/shared/Testimonials";
import { Toaster } from "@/components/ui/sonner";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "slick-carousel/slick/slick-theme.css";
import "slick-carousel/slick/slick.css";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} bg-[#F0F0F0]`}>
        <ApolloWrapper>
          <Header />
          {children}
          <Testimonials />
          <BlogCardPreview />

          <Footer />
          <Toaster />
        </ApolloWrapper>
      </body>
    </html>
  );
}
