import Footer from "@/app/(mainLayout)/footer";
import "@/app/globals.css";
import ApolloWrapper from "@/components/apollo/ApolloWrapper";
import Header from "@/components/header/Header";
import BlogCardPreview from "@/components/news-letter/BlogCardPreview";
import GoogleTranslateWidget from "@/components/shared/GoogleTranslateWidget";
import Testimonials from "@/components/shared/Testimonials";
import { Toaster } from "@/components/ui/sonner";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "slick-carousel/slick/slick-theme.css";
import "slick-carousel/slick/slick.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Omni HealthCare",
  description: "Generated by Omni HealthCare",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script
          type="text/javascript"
          src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"
          async
        ></script>
      </head>
      <body className={`${poppins.variable} bg-[#F0F0F0]`}>
        <ApolloWrapper>
          <GoogleTranslateWidget /> {/* Hidden initialization */}
          <Header></Header>
          {children}
          <Testimonials />
          <BlogCardPreview />
          <Footer />
          <Toaster />
        </ApolloWrapper>
      </body>
    </html>
  );
}
